# ALinux container configuration
container.id=ubuntu
container.hostname=ubuntu-android
container.user=root
container.workdir=/root
ssh.port=2224
ssh.password=root
image.url=https://mirrors.aliyun.com/ubuntu-cdimage/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.4-base-arm64.tar.gz
